[msg msg_combine_HELP004 [Igor]]
[s][bup 15 161 0 1]Una Persona creada mediante fusión[n]puede heredar las habilidades[n]de sus precursoras.[n][w][e]
[s]En otras palabras, es posible darle[n]a una Persona habilidades que jamás[n]aprendería por su cuenta.[n][w][e]
[s]Deberías tener esto presente cuando[n]intentes crear una Persona poderosa.[n][w][e]
[s]El mecanismo de la herencia de[n]habilidades no está estudiado del todo.[n][w][e]
[s]Pero hay dos puntos clave que[n]me gustaría compartir contigo.[n][w][e]
[s]Primero, la posibilidad de que[n]se herede una habilidad depende[n]de la Persona esperada.[n][w][e]
[s]Puedo darte más detalles al respecto[n]en otro momento.[n][w][e]
[s]Segundo, cuantas más habilidades[n]tengan las Personas originales, más[n]habilidades recibirá la nueva.[n][w][e]
[s]No lo olvides.[n][w][e]

[msg combine_skill_choose [Igor]]
[s]Elige las habilidades[n]que te gustaría transferir.[n][w][e]

